# Use Travis's container-based infrastructure.
sudo: false

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install coveralls

script:
  coverage run --source=flask_restless setup.py test

after_success:
  coveralls
